### ISSUE TITLE
how do i hide the watermark

### ISSUE THREAD

**Issue by ammystic** [deadshxll/fusion#39]
i wanna screenshare my game while 1v1ing my friends with fusion but they would see this watermark so im just wondering if there is anyway to hide it.
![image](https://github.com/deadshxll/fusion/assets/150622366/56ee949a-94ce-41c6-9cd1-0af392a4dc8e)

**Comment by ammystic** [comment]
nevermind i found it.
renderLoop.cpp

**Comment by deadshxll** [comment]
👍
